### ISSUE TITLE
Add support for API-Key protected /slots endpoint introduced in llama.cpp b3898

### ISSUE THREAD

**Issue by countzero** [distantmagic/paddler#23]
### Description

Since the llama.cpp release [b3898](https://github.com/ggerganov/llama.cpp/releases/tag/b3898) the `/slots` API endpoint is secured with an API key if it's set.

This is a documented breaking change: [changelog : llama-server REST API](https://github.com/ggerganov/llama.cpp/issues/9291) 

### Implications for Paddler

The paddler agent needs access to the  `/slots` API endpoint to determine the load on the [llama-server](https://github.com/ggerganov/llama.cpp/tree/b3898/examples/server).

### Suggestion

Add a new option `--llama-server-api-key` to configure the `paddler agent`. Use the API key in requests to the `/slots` API endpoint.

### Context

The API key implementation of `llama.cpp` mirrors the [OpenAI API Authentication](https://platform.openai.com/docs/api-reference/authentication). The following HTTP header is expected in requests to a `llama-server` instance that is secured via either the `--api-key` or the `--api-key-file` option:

```
Authorization: Bearer LLAMA_API_KEY
```

**Comment by mcharytoniuk** [comment]
@countzero Thank you for your detailed report! This feature is implemented in `0.9.0` behind `--local-llamacpp-api-key` in `paddler agent`.
