### ISSUE TITLE
Req for windows Build

### ISSUE THREAD

**Issue by jkfnc** [distantmagic/paddler#8]
Thanks for making this, is it possible to include windows builds as part of releases ?

**Comment by mcharytoniuk** [comment]
Will do. :) Follow this issue to stay posted. I will get to it this week.

**Comment by mcharytoniuk** [comment]
@jkfnc I have added Windows and MacOS binaries to the latest Paddler release. From now on, those OSs will be included by default in Paddler releases. :) 

If you need any other OS to be included, either let me know or make a PR and add it to the build matrix: https://github.com/distantmagic/paddler/blob/main/.github/workflows/release.yml

https://github.com/distantmagic/paddler/releases/tag/v0.3.0

**Comment by jkfnc** [comment]
Thanks, working good.  But the management-server crashed two times, will try to replicate next time, is there way to enable debug level logs.

**Comment by mcharytoniuk** [comment]
@jkfnc If you want, we can debug that together. 

I recently covered multi-GPU setup issues in [v4.0.0 release](https://github.com/distantmagic/paddler/releases/tag/v0.4.0). There might be some issues under Windows as well.

If you can spend some time on it, you can share your screen on Discord, and we can debug that case, too.

**Comment by mcharytoniuk** [comment]
@jkfnc I just released `v0.5.0`. I checked it against all races and potential threading issues I could find. I don't know exactly what caused the specific issue you mentioned, but there is a chance that `v0.5.0` won't crash under Windows anymore.

**Comment by jkfnc** [comment]
Thanks, will try it out and let you know..
